apiVersion: v1
kind: ReplicationController
metadata:
  name: simplejava-controller
spec:
  replicas: 3
  selector:
    app: simplejava
  template:
    metadata:
      labels:
        app: simplejava
    spec:
      containers:
      - name: simple-java
        image: itstharun/sample-maven:version1
        ports:
        - name: java-port
          containerPort: 3000
